### ISSUE TITLE
⚒️ Build content warning logic

### ISSUE THREAD

**Issue by tatianamac** [selfdefined/web-app#142]
## Overview
Content warnings are current listed as a label, so it shows up on the homepage. It's looking a bit cluttered and lacks context.

Instead, the content warning flag should trigger adding a note to a word definition page to the effect of:

"You may want to add a content warning before discussing or showing imagery involving this topic, as it is a topic that can elicit negative feelings and visceral reactions like a panic attack or trauma. Content warnings usually take the form of: "Content warning: [topic]" and should precede the subject matter. Please ensure your content warnings are accessible."

**Comment by MatthewShields** [comment]
@tatianamac I can take a look at this one :) just to check a couple of things though:

1. alongside the adding of the note to the individual definition page, because you have mentioned the homepage looking cluttered would you want them removing from the homepage?

2. if this is the case would you want to keep the other homepage red flags such as racist or sexist terms?

**Comment by MatthewShields** [comment]
I have approached it like this, however as this has involved design decisions it would be good to get your input as I don't want to mess with the aesthetic of the site.

I have added an introductory section (when a flag is present) with an anchor link to a section at the bottom. My thought process on this was that it would allow the guidance on content warnings to be expanded if necessary without disrupting the definition content.

### Screenshots

Top:
![image](https://user-images.githubusercontent.com/1742467/82139787-44467680-9822-11ea-9cef-efc833079a3a.png)

Bottom:
![image](https://user-images.githubusercontent.com/1742467/82139864-fb42f200-9822-11ea-8f65-be5b99126009.png)

There is the capability to have separate flag content between the amber and red level definitions.

<hr>

### Selection styling

I have also added selection styling to the .box class incase someone ever needs to copy content from the content warning guidance:

![image](https://user-images.githubusercontent.com/1742467/82139933-b075aa00-9823-11ea-8aec-a442d7386193.png)

**Comment by tatianamac** [comment]
Hi @MatthewShields ! This is awesome, thank you so much for taking a pass at this!

I'd love to see a few things for if/when you decide to open a pull request:
- Integrate the content warning style (yellow instead of red, with the ⚠️ iconography) into the top and bottom boxes (so light yellow background on both, perhaps with that red line to yellow? 
- I think that the "Content warning: [topic]" sentence could use a little work (which is my bad). Perhaps it reads" "Content warnings usually take the form of "Content warning: [topic(s)]" or "CW: [topic(s)]. We recommend the former when possible.

**Comment by tatianamac** [comment]
As for your questions, I think that at some point, we'll probably no longer have this "all words" view, and the homepage will function a bit more as a explainer as to what this tool is, and perhaps we'll have all the tags linked under a "avoid terms" list. Until then, I think it's good to keep them as a cursory glance; the content warning just sent it a bit over the visual overload edge.

**Comment by MatthewShields** [comment]
Great thanks for the input will get onto working on the changes now :)

Will keep the flags on the homepage but if you want an extra set of hands in the future working on that feel free to @ me.

**Comment by tatianamac** [comment]
I always appreciate extra help! Also, I have opened up Self-Defined Saturdays on Slack so folks can get input and collaborate (and I can offer centralised, immediate help), if [you'd like to join](https://join.slack.com/t/selfdefined/shared_invite/zt-en1u6xn8-CumcehUfprC0GH5lamb1bg)!

**Comment by MatthewShields** [comment]
@tatianamac I think we can mark this issue as closed now?

**Comment by ovlb** [comment]
@MatthewShields I’ve linked the PR so that both open issues get auto-closed.
