### ISSUE TITLE
Introduce RSS/Atom feed

### ISSUE THREAD

**Issue by katesowles** [selfdefined/web-app#149]
- allows folks to subscribe and keep up to date with new additions
- to check: curious if RSS/Atom can be setup to push edits/updates as well

And of course 11ty has a plugin for this: https://www.11ty.dev/docs/plugins/rss/

**Comment by katesowles** [comment]
New to 11ty but I'll give this one a shot since (selfishly) I want updates pushed to me in a more manageable format than twitter.

**Comment by ovlb** [comment]
As the docs are not finished please don’t hesitate to ask if anything is unclear!

**Comment by tatianamac** [comment]
Closed per #192 (had to manually close due to main branch name change and new PR opened).
