### ISSUE TITLE
 ⚒️ Show definition in unfurled social views

### ISSUE THREAD

**Issue by tatianamac** [selfdefined/web-app#179]
## Current Behaviour
Right now the description says "Definition of [word] in Self-Defined, a modern dictionary about us:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/7484549/83340162-bb035b00-a289-11ea-9824-28fbdea51179.png">

## Desired Behaviour
Instead, it'd be great if the social card/unfurled view l could include the definition

**Comment by tbrasington** [comment]
Hello

Is there a preference on how this should be for writers? 

I have had these ideas so far :

1. add a front matter tag like this:

```
---
title: Example Word
slug: 'example-word'
speech: noun
defined: true
excerpt: This is a sentence. It describes a word. This definition is written in Markdown. 
---
```

2. use a tag like **`<!-- excerpt -->`** which would take the content above it:

```
---
title: Example Word
slug: 'example-word'
speech: noun
defined: true
---

This is a sentence. It describes a word. This definition is written in Markdown. So you can do stuff. [Including links](/link), for example.

<!-- excerpt -->

The rest of the page content is here
```

Both could be implemented in the definition.njk file like this and falling back to the existing description if no text is present

```
{% set description = excerpt if excerpt | length > 0 else 'The definition of ' + title + ' in Self-Defined, a modern dictionary about us.' %}
```


Looking forward to hearing the feedback and ideas

Thank you
