### ISSUE TITLE
Suggestion: Colorblind

### ISSUE THREAD

**Issue by AutoSponge** [selfdefined/web-app#185]
I heard a colleague use the term, "color blind" (like it was a good thing) during a recent discussion about race. I don't use the term, even in sarcasm, because it conflates with people who actually have color blindness. Perhaps it's ableist? In this context it's certainly racist.

~~However, if I use the term "post-racial" to describe someone, they're living in a fantasy world. They're so removed from the conversation by their privilege, they might as well be on another planet. As in "Don't let Karen speak at this event, she's 'post-racial' [and likely to say something awful]."~~ concentrate on one term at a time.

Category: micro-aggression

**Comment by AutoSponge** [comment]
Possible resources:
> Colorblind Racism
Social changes did not eliminate racism and racial inequality, even if they made important progress. But, if racism is no longer overt in many situations yet still exists, what should we call it? One concept which scholars call colorblind racism, is the belief that racism is no longer a problem and that we all have equal opportunities. People who subscribe to colorblind explanations claim they do not see the color of people's skin and believe everyone to be equal. Colorblindness prevents us from seeing the historical causes of racial inequality and how racial inequality persists in our society.

https://study.com/academy/lesson/color-blind-racism-definition-theory-examples.html

> Colorblindness is the racial ideology that posits the best way to end discrimination is by treating individuals as equally as possible, without regard to race, culture, or ethnicity.
At its face value, colorblindness seems like a good thing—really taking MLK seriously on his call to judge people on the content of their character rather than the color of their skin. It focuses on commonalities between people, such as their shared humanity.
However, colorblindness alone is not sufficient to heal racial wounds on a national or personal level. It is only a half-measure that in the end operates as a form of racism.

https://www.psychologytoday.com/us/blog/culturally-speaking/201112/colorblind-ideology-is-form-racism

> THE COMMON IDEA of claiming “color blindness” is akin to the notion of being “not racist”—as with the “not racist,” the color-blind individual, by ostensibly failing to see race, fails to see racism and falls into racist passivity. The language of color blindness—like the language of “not racist”—is a mask to hide racism.

> Terms and sayings like “I’m not racist” and “race neutral” and “post-racial” and “color-blind” and “only one race, the human race” and “only racists “speak about race” and “Black people can’t be racist” and “White people are evil” are bound to fail in identifying and eliminating racist power and policy.

Excerpts From: Ibram X. Kendi. “How to Be an Antiracist.”

> ...post-racial theory is quite possibly the most sophisticated racist ideology ever created.

Summary: There's only two explanations for racial inequalities in America. It's either racial discrimination or there's something wrong with Black people. The post-racial theory would have you believe there's no such thing as racial discrimination (any more). Which only leaves room for the racist idea that there's something wrong or inferior with Black people.

Quote and summary from https://www.youtube.com/watch?v=nBFYQu1ZYD0&t=605s

> This is a classic microagression: the assumption that you get to drive other people’s conversations. You say you want to be colorblind while using your privilege to attempt to silence someone else, where it is neither the time or place for that debate.

https://medium.com/@tinu/what-you-erase-when-you-say-i-dont-see-color-73360346afa7

> Please - if you are calling out racism/white supremacy - don’t use “deaf” or “blind” when you really mean ignorant, not listening, etc. Being blind or deaf doesn’t mean = ignorant. 

(Caroline Bailey) https://twitter.com/cmbaileyatx/status/1269734632095911937

Still researching...

**Comment by tatianamac** [comment]
I think that color-blind is definitely a good term to parse out of this.

As for post-racial, I think it could be effective too, so long as the definition is clear about "Appropriate and Inapprorpiate Usages" (this is a common construction we use in the dictionary).

**Comment by AutoSponge** [comment]
I had a coworker talk about this, "you do see color, you just may not use color to drive your feelings and outcomes, but then even that isn't true." I'd still like to get this into a PR but lack conviction about how to frame it.
